In [514]:
#!/usr/bin/python
# -*- encoding: iso-8859-1 -*-

import sys
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
from sklearn.metrics import f1_score

In [474]:
path = "../ex01_repr/features.txt"

In [494]:
print ("Loading data...")
data = np.loadtxt(path)
X_data = data[:, 0:len(data[0])-1]
y_data = data[:,len(data[0])-1]
X_data = normalize(X_data)

Loading data...


In [495]:
print ("Spliting data...")
X_train, X_test, y_train, y_test =  train_test_split(X_data, y_data, test_size=0.3, random_state = 5)

Spliting data...


In [496]:
# cria um kNN
neigh = KNeighborsClassifier(n_neighbors=3, metric='l1')

In [498]:
print ('Fitting knn')
neigh.fit(X_train, y_train)

Fitting knn


KNeighborsClassifier(metric='l1', n_neighbors=3)

In [499]:
# predicao do classificador
print ('Predicting...')
y_pred = neigh.predict(X_test)

Predicting...


In [500]:
# mostra o resultado do classificador na base de teste
print ('Accuracy: ',  neigh.score(X_test, y_test))

Accuracy:  0.9283333333333333


In [493]:
# cria a matriz de confusao
cm = confusion_matrix(y_test, y_pred)
print (cm)
print(classification_report(y_test, y_pred))

[[54  0  0  0  0  1  0  0  0  0]
 [ 0 50  0  0  0  0  0  0  0  0]
 [ 1  3 59  1  0  0  0  1  0  1]
 [ 0  0  0 68  0  0  0  0  0  0]
 [ 0  5  1  0 54  0  0  0  0  0]
 [ 1  0  0  3  0 52  0  0  0  0]
 [ 2  1  0  0  1  1 61  0  0  0]
 [ 0  1  0  0  0  0  0 54  0  1]
 [ 0  1  1  3  0  2  1  0 43  1]
 [ 0  0  0  0  3  0  0  6  0 62]]
              precision    recall  f1-score   support

         0.0       0.93      0.98      0.96        55
         1.0       0.82      1.00      0.90        50
         2.0       0.97      0.89      0.93        66
         3.0       0.91      1.00      0.95        68
         4.0       0.93      0.90      0.92        60
         5.0       0.93      0.93      0.93        56
         6.0       0.98      0.92      0.95        66
         7.0       0.89      0.96      0.92        56
         8.0       1.00      0.83      0.91        52
         9.0       0.95      0.87      0.91        71

    accuracy                           0.93       600
   macro avg       

In [526]:
num_iter = 5
acc = 0
sum_cm = np.zeros((10, 10))
f1 = 0
for i in range(num_iter):
    print ("Spliting data...")
    X_train, X_test, y_train, y_test =  train_test_split(X_data, y_data, test_size=0.3)

    # cria um kNN
    neigh = KNeighborsClassifier(n_neighbors=3, metric='l1')

    print ('Fitting knn')
    neigh.fit(X_train, y_train)

    # predicao do classificador
    print ('Predicting...')
    y_pred = neigh.predict(X_test)

    # mostra o resultado do classificador na base de teste
    acc += neigh.score(X_test, y_test)

    # cria a matriz de confusao
    cm = confusion_matrix(y_test, y_pred)
    sum_cm += cm
    
    f1 += f1_score(y_test, y_pred, average='weighted')
    
print ('Accuracy: ', acc/num_iter)
print(np.around(sum_cm.astype('float') / sum_cm.sum(axis=1)[:, np.newaxis], decimals=2))
print('F1 score: ', f1/num_iter)

Spliting data...
Fitting knn
Predicting...
Spliting data...
Fitting knn
Predicting...
Spliting data...
Fitting knn
Predicting...
Spliting data...
Fitting knn
Predicting...
Spliting data...
Fitting knn
Predicting...
Accuracy:  0.923
[[0.99 0.   0.   0.   0.   0.01 0.   0.   0.   0.  ]
 [0.   0.99 0.01 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.02 0.9  0.   0.   0.   0.   0.05 0.01 0.  ]
 [0.   0.   0.   0.96 0.   0.02 0.   0.01 0.01 0.  ]
 [0.   0.08 0.   0.   0.89 0.   0.   0.   0.   0.02]
 [0.   0.01 0.   0.04 0.   0.91 0.01 0.01 0.   0.01]
 [0.02 0.   0.   0.   0.   0.   0.98 0.   0.   0.  ]
 [0.   0.02 0.   0.   0.01 0.   0.   0.94 0.   0.03]
 [0.02 0.04 0.01 0.08 0.01 0.01 0.   0.   0.8  0.02]
 [0.   0.01 0.   0.   0.02 0.   0.   0.08 0.   0.88]]
F1 score:  0.9227894404205029
